<script>
var stateObject = {
     "Hindu": {
         "Naidu":["Naidu", "Kammavar", "Balija", "Kavara", "Vellama", "Raja Kambalam", "Muthuraja Peiyar", "Ekari", "Ettiga", "Basetha", "Kalinki", "Kappu", "Kolla Thotiya Nayar"],
		 "Pillaimar": ["Saiva Pillaimar", "Asaiva Pillaimar", "Kottikal", "Soliya Vellalar", "Thuluva Vellalar", "Mottu Vellam", "Karak Katu"],
        "Devendragula Velalar": ["Others"],
		"Vanniyar": ["Others"],
        "Maruthuvar":["Others"],
		 "Kallar": ["Others"],
        "Yadhavar":["Others"],
		 "Nadar": ["Gramani/sanar", "Kongu Nadar", "Nadar", "Yadavar", "Reddyar", "Arunthathiyar", "Aasariyar", "Vannar", "Vanniyar", "Others"],
       
		"Adhithiravidar": ["Others"],
        "Vishvakarma":["Others"],
		 "Chettiyar": ["Others"],
        "Christians":["Others"],
		 "Muthaliyar": ["Others"],
        "Vannaar":["Others"],
		 "Iyer": ["Others"],
        "Reddiyar":["Others"],
		 "Veerasaivam": ["Others"],
        "Muslim":["Others"],
		 "Moopanar": ["Others"],
        "Arundhathiyar":["Others"],
		 "Nayakkar": ["Others"],
        "Saliyar":["Others"],
		 "Gowndar":["Others"],
		 "Velalar": ["Vellalar", "Saiva Vellalar", "Anaithu Vellalar"],
        "Rajukkal":["Others"],
		 "Kuravar":["Others"],
		 "Poyar": ["Others"],
        "Valluvan":["Others"],
		 "Meenavar":["Others"],
		 "Marumanam": ["Others"],
        "Aghamudaiyar":["Devar","Servai", "Muthaliyar -PR-PL", "Udaiyar", "Mukkulathor", "Sengunthar Kodi", "Kallar", "Maravar", "Moopanar", "Maruthuvar", "Veera Saivam","Gounder"],
		 "Maniyan":["Others"],
		 "Kannada Pagadaiyar": ["Others"],
        "Pandaram":["Others"],
		 "Maravar":["Others"],
		 "Sourashtra": ["Others"],
		  "Paraiyar": ["Others"],
       
        "Naayar":["Others"],
		"Udaiyar":["Others"],
		"Not Necessary":["Others"],
		"No Importance":["Others"],
		
		

	},
    "Muslim-Shia": {
  "Muslim-Ansari": ["Others"],
  "Muslim-Bohra":["Others"],
  "Muslim-Dekkani":["Dekkani", "Others","Don't wish to specify"],
 "Muslim-Dudekula":["Dudekula", "Others","Don't wish to specify"],
   "Muslim-Hanafi":["Hanafi", "Others","Don't wish to specify"],
     "Muslim-Jat":["Jat", "Others","Don't wish to specify"],
 "Muslim-Khoja":["Khoja", "Others","Don't wish to specify"], 
"Muslim-Malik":["Malik", "Others","Don't wish to specify"],
 "Muslim-Mapila": ["Mapila", "Others"],
  "Muslim-Maraciar":["Maraciar", "Others","Don't wish to specify"],
  "Muslim-Memom":["Memom", "Others","Don't wish to specify"],
 "Muslim-Mughal":["Mughal", "Others","Don't wish to specify"],
  
     "Muslim-Pathan":["Pathan", "Others","Don't wish to specify"],
	   "Muslim-Qureshi":["Qureshi", "Others","Don't wish to specify"], 
	    "Muslim-Rajput":["Rajput", "Others","Don't wish to specify"],
		 "Muslim-Rowther":["Rowther", "Others","Don't wish to specify"],
     "Muslim-Shafi":["Shafi", "Others","Don't wish to specify"],
	   "Muslim-Sheikh":["Sheikh", "Others","Don't wish to specify"], 
	    "Muslim-Siddiqui":["Siddiqui", "Others","Don't wish to specify"],
		  "Muslim-Syed":["Syed", "Others","Don't wish to specify"],
		   "Muslim-Other":["Others"],
		   "Muslim-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
    }
	,
    "Muslim-Sunni": {
       "Muslim-Ansari": ["Ansari", "Others"],
  "Muslim-Bohra": ["Others"],
  "Muslim-Dekkani":["Others"],
 "Muslim-Dudekula":["Others"],
   "Muslim-Hanafi":["Others"],
     "Muslim-Jat":["Others"],
 "Muslim-Khoja":["Others"], 
"Muslim-Malik":["Others"],
 "Muslim-Mapila": ["Others"],
  "Muslim-Maraciar":["Others"],
  "Muslim-Memom":["Others"],
 "Muslim-Mughal":["Others"],
  
     "Muslim-Pathan":["Others"],
	   "Muslim-Qureshi":["Others"], 
	    "Muslim-Rajput":["Others"],
		 "Muslim-Rowther":["Others"],
     "Muslim-Shafi":["Others"],
	   "Muslim-Sheikh":["Others"], 
	    "Muslim-Siddiqui":["Others"],
		  "Muslim-Syed":["Others"],
		   "Muslim-Other":["Others"],
		   "Muslim-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
    }
	,
    "Muslim-Others": {
        "Muslim-Ansari": ["Others"],
  "Muslim-Bohra":["Others"],
  "Muslim-Dekkani":["Others"],
 "Muslim-Dudekula":["Others"],
   "Muslim-Hanafi":["Others"],
     "Muslim-Jat":["Others"],
 "Muslim-Khoja":["Others"], 
"Muslim-Malik":["Others"],
 "Muslim-Mapila": ["Others"],
  "Muslim-Maraciar":["Others"],
  "Muslim-Memom":["Others"],
 "Muslim-Mughal":["Others"],
  
     "Muslim-Pathan":["Others"],
	   "Muslim-Qureshi":["Others"], 
	    "Muslim-Rajput":["Others"],
		 "Muslim-Rowther":["Others"],
     "Muslim-Shafi":["Others"],
	   "Muslim-Sheikh":["Others"], 
	    "Muslim-Siddiqui":["Others"],
		  "Muslim-Syed":["Others"],
		   "Muslim-Other":["Others"],
		    "Muslim-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
			 
    }
	,
    "Christian": {
        "Anglo Indian": ["Others"],
        "Basel Mission":["Others"],
		 "Born Again": ["Others"],
        "Bretheren":["Others"],
		 "Cannonite": ["Others"],
        "Catholic":["Others"],
		 "Catholic Knanya": ["Others"],
        "Catholic Malankara":["Others"],
		 "Chaldean Syrian": ["Others"],
        "Cheramar christian":["Others"],
		 "Church of North India (CNI)": ["Others"],
        "Church of South India (CSI)":["Others"],
		 "CMS": ["Others"],
        "Convert":["Others"],
		 "Evangelical": ["Others"],
        "Indian Orthodox":["Others"],
		 "Intercaste christian": ["Others"],
        "IPC":["Others"],
		 "Jacobite": ["Others"],
        "Jacobite Knanya":["Others"], 
		"Knanaya": ["Others"],
        "Knanaya Jacobite":["Others"],
		 "Knanaya Pentecostal": ["Others"],
        "Knanya":["Others"],
		 "Latin Catholic": ["Others"],
        "Malankara":["Others"],
		 "Malankara Catholic": ["Others"],
        "Manglorean":["Others"],
		 "Marthoma": ["Others"],
        "Methodist":["Others"],
		 "More": ["Others"],
        "Mormon":["Others"],
		"Nadar christian": ["Others"],
        "Orthodox":["Others"],
		"Pentecost": ["Others"],
        "Presbyterian":["Others"],
		"Protestant": ["Others"],
        "RCSC":["Others"],
		 "Roman Catholic":["Others"],
		  "Salvation Army":["Others"],
		   "Scheduled Caste (SC) christian":["Others"],
		    "Scheduled Tribe christian (ST) ":["Others"],
 "Seventh day Adventist": ["Others"],
        "Syrian":["Others"],
		 "Syrian Catholic": ["Others"],
        "Syrian Orthodox":["Others"],
		 "Syro Malabar": ["Others"],
      "Christian-Other":["Others"],
		    "Christian-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
    }
	,
    "Sikh": {
        "Sikh-Ahluwalia": ["Others"],
        "Sikh-Arora":["Others"],
		"Sikh-Bhatia": ["Others"],
        "Sikh-Bhatra":["Others"],
		"Sikh-Ghumar": ["Others"],
        "Sikh-Jat":["Others"],
		"Sikh-Kamboj": ["Others"],
        "Sikh-Khatri":["Others"],
		"Sikh-Kshatriya": ["Others"],
        "Sikh-Lubana":["Others"],
		"Sikh-Majabi": ["Others"],
        "Sikh-Nai":["Others"],
		"Sikh-Rajput": ["Others"],
        "Sikh-Ramdasia":["Others"],
		"Sikh-Ramgharia": ["Others"],
        "Sikh-Ravidasia":["Others"],
		"Sikh-Saini": ["Others"],
         "Sikh-Other":["Others"],
		    "Sikh-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
    }
	,
    "Jain-Digambar": {
        "Jain-Agrawal": ["Others"],
        "Jain-Arasu":["Others"],
		 "Jain-Asathi Vaishya": ["Others"],
        "Jain-Ayodhyavasi":["Others"],
		 "Jain-Baghel": ["Others"],
        "Jain-Bakarwal":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Bannore":["Others"],
		 "Jain-Baraiya": ["Others"],
        "Jain-Bhabra":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Bhavsar":["Others"],
		 "Jain-Bhojak": ["Others"],
        "Jain-Bogar":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Chaturth":["Others"],
		 "Jain-Chitoda": ["Others"],
        "Jain-Dhakad":["Others"],
		 "Jain-Dharmpal": ["Others"],
        "Jain-Gangerwal":["Others"],
		 "Jain-Jaiswal": ["Others"],
        "Jain-KVO":["Others"],
		 "Jain-Khandelwal": ["Others"],
        "Jain-kutchi":["Others"],
		 "Jain-Oswal": ["Others"],
        "Jain-Porwal":["Others"],
		 "Jain-Vaishya": ["Others"],
         "Jain-Other":["Others"],
		    "Jain-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
    }
	,
    "Jain-Shwetambar": {
         "Jain-Agrawal": ["Others"],
        "Jain-Arasu":["Others"],
		 "Jain-Asathi Vaishya": ["Others"],
        "Jain-Ayodhyavasi":["Others"],
		 "Jain-Baghel": ["Others"],
        "Jain-Bakarwal":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Bannore":["Others"],
		 "Jain-Baraiya": ["Others"],
        "Jain-Bhabra":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Bhavsar":["Others"],
		 "Jain-Bhojak": ["Others"],
        "Jain-Bogar":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Chaturth":["Others"],
		 "Jain-Chitoda": ["Others"],
        "Jain-Dhakad":["Others"],
		 "Jain-Dharmpal": ["Others"],
        "Jain-Gangerwal":["Others"],
		 "Jain-Jaiswal": ["Others"],
        "Jain-KVO":["Others"],
		 "Jain-Khandelwal": ["Others"],
        "Jain-kutchi":["Others"],
		 "Jain-Oswal": ["Others"],
        "Jain-Porwal":["Others"],
		 "Jain-Vaishya": ["Others"],
         "Jain-Other":["Others"],
		    "Jain-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
    }
	,
    "Jain-Others": {
        "Jain-Agrawal": ["Others"],
        "Jain-Arasu":["Others"],
		 "Jain-Asathi Vaishya": ["Others"],
        "Jain-Ayodhyavasi":["Others"],
		 "Jain-Baghel": ["Others"],
        "Jain-Bakarwal":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Bannore":["Others"],
		 "Jain-Baraiya": ["Others"],
        "Jain-Bhabra":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Bhavsar":["Others"],
		 "Jain-Bhojak": ["Others"],
        "Jain-Bogar":["Others"], "Jain-Digambar": ["Others"],
        "Jain-Chaturth":["Others"],
		 "Jain-Chitoda": ["Others"],
        "Jain-Dhakad":["Others"],
		 "Jain-Dharmpal": ["Others"],
        "Jain-Gangerwal":["Others"],
		 "Jain-Jaiswal": ["Others"],
        "Jain-KVO":["Others"],
		 "Jain-Khandelwal": ["Others"],
        "Jain-kutchi":["Others"],
		 "Jain-Oswal": ["Others"],
        "Jain-Porwal":["Others"],
		 "Jain-Vaishya": ["Others"],
         "Jain-Other":["Others"],
		    "Jain-Unspecified":["Others"],
			 "Don't Wish to specify":["Others"],
    }
	,
    "Parsi": {
        "Irani": ["Others"],
        "Parsi":["Others"],
		 "Intercaste": ["Others"],
        "Other Caste":["Others"],
		 "Don't Wish to specify":["Others"],
    }
	,
    "Buddhist": {
       "Other Caste":["Others"],
		 "Don't Wish to specify":["Others"],
    }
	,
    "Jewish": {
        "Other Caste":["Others"],
		 "Don't Wish to specify":["Others"],
    }
	,
    "Inter Religion": {
        "Chettiar": ["Others"],
        "Aaru Nattu Vellala":["Others"],
		 "Ad Dharmi": ["Others"],
        "Adi Karnataka": ["Others"]
		, "96 Kuli Maratha": ["Others"],
        "Achirapakkam Chettiar":["Others"],
		 "Adi Dravidar": ["Others"],
        "Adi Karnataka":["Others"],
		 "Agamudayar": ["Others"],
        "Chettiar":["Others"],
		"Agarwal": ["Others"],
        "Agnikula Kshatriya":["Others"],
		 "Agrahari": ["Others"],
        "Ahir Shimpi":["Others"],
		 "Ahirwar": ["Others"],
        "Ahom":["Others"],
		 "Ambalavasi": ["Others"],
        "Anjana (Chowdary) Patel":["Others"],
		 "Aramari": ["Others"],
        "Arekatica":["Others"],
		 "Arora": ["Others"],
        "Arunthathiyar":["Others"],
		 "Arya Vysya": ["Others"],
        "Asathi":["Others"],
		 "Ayira Vysya":["Others"],
		 "Ayodhyavasi": ["Others"],
        "Ayyaraka":["Others"],
		 "Badaga":["Others"],

		 "Bagdi": ["Others"],
        "Baishnab":["Others"],
		 "Balija":["Others"],
		 "Banayat Oriya": ["Others"],
        "Baniya - Bania":["Others"],
		 "Barai":["Others"],
		 "Barnwal": ["Others"],
        "Brahmin":["Others"],
		 "Brajastha Maithil":["Others"],
		 "Bunt": ["Others"],
        "CKP":["Others"],
		"Chalawadi and Holeya":["Others"],
		"Chambhar":["Others"],
		"Chandravanshi Kahar":["Others"],
		"Chattada Sri Vaishnava":["Others"],
		"Chaturth":["Others"],
		"Chaurasia":["Others"],
		"Chaudary":["Others"],
		"Chaurasia":["Others"],
		"Chennadasar":["Others"],
		"Cherakula Vellalar":["Others"],
		"Chhetri":["Others"],
		"Chippolu":["Others"],
		"Chaurasia":["Others"],
		"Desikar":["Others"],
		"Devadiga":["Others"],
		"Devandra Kula Vellalar":["Others"],
		"Devang Koshthi":["Others"],
		"Devanga":["Others"],
		"Devanga Chettiar":["Others"],
		"Devar/Thevar/Mukkulathor":["Others"],
		"Devrukhe Brahmin":["Others"],
		"Dhanak":["Others"],
		"Dhangar":["Others"],
		"Dheevara":["Others"],
		"Dhiman":["Others"],
		"Dhobi":["Others"],
		"Dommala":["Others"],
		"Dhanak":["Others"],
		"Dosar":["Others"],
		"Dumal":["Others"],
		"Dusadh":["Others"],
		"Ediga":["Others"],
		"Elur Chetty":["Others"],
		"Ezhava":["Others"],
		"Gabit":["Others"],
		"Gahoi":["Others"],
		"Gajula / Kavarai":["Others"],
		"Gandha Vanika":["Others"],
		"Gandla":["Others"],
		"Gavara":["Others"],
		"Gawali":["Others"],
		"Ghisadi":["Others"],
		"Ghumar":["Others"],
		"Goala":["Others"],
		"Goan":["Others"],
		"Gomantak":["Others"],
		"Gondhali":["Others"],
		"Gounder": [" Others"],
		"Gowda": ["Others"],
		"Gramani":["Others"],
"Guptan":["Others"],
"Gujjar":["Others"],
"Haihaivanshi":["Others"],

"Hugar":["Others"],
"Jaiswal":["Others"],
"Irani":["Others"],
"Jaalari":["Others"],
"Jangam":["Others"],
"Jat":["Others"],
"Jetty/Malla":["Others"],
"Jogi":["Others"],
"Kaibarta":["Others"],
"Kachara":["Others"],
"Kadava Patel":["Others"],
"Kahar":["Others"],
"Kaikaala": ["Others"],
"Kalal": ["Others"],
"Kalanji": ["Others"],
"Kalar": ["Others"],
"Kalinga": ["Others"],
"Kalita": ["Others"],
"Kalwar": ["Others"],
"Kamboj": ["Others"],
"Kamma": ["Others"],
"Kamma Naidu": ["Others"],
"Kanakkan Padanna": ["Others"],
"Kandara": ["Others"],
"Kansari": ["Others"],
"Kapu": ["Kapu Naidu", "Kapu Reddy"],
"Karakala Bhakthula": ["Others"],
"Karana": ["Others"],
"Karkathar": ["Others"],
"Karmakar": ["Others"],
"Karni Bhakthula": ["Others"],
"Karuneegar": ["Others"],
"Kasar": ["Others"],
"Kasaundhan": ["Others"],
"Kashyap": ["Others"],
"Kasukara": ["Others"],
"Katiya": ["Others"],
"Kavara": ["Others"],
"Kavuthiyya/Ezhavathy": ["Others"],
"Kayastha": ["Others"],
"Keshri": ["Others"],
"Khandayat": ["Others"],
"Khandelwal": ["Others"],
"Khatik": ["Others"],
"Kirar": ["Others"],
"Kodikal Pillai": ["Others"],
"Kokanastha Maratha": ["Others"],
"Koli": ["Koli", "Koli Mahadev","Koli Patel"],
"Konkani": ["Others"],
"Kunbi": ["Kunbi Lonari", "Kunbi Maratha","Kunbi Tirale"],	
"Lad": ["Others"],	
"Lambadi": ["Others"],	
"Leva patel": ["Others"],
"Leva patil": ["Others"],
"Linga Balija": ["Others"],
"Lingayath": ["Others"],
"Lodhi Rajput": ["Others"],
"Lohana": ["Others"],
"Lohar": ["Others"],
"Loniya": ["Others"],
"Lubana": ["Others"],
"Madhesiya/Kanu/Halwai": ["Others"],
"Madiga": ["Others"],
"Mahajan": ["Others"],
"Mahar": ["Others"],
"Mahendra": ["Others"],
"Maheshwari": ["Others"],
"Mahishya": ["Others"],
"Mahor": ["Others"],
"Mahuri": ["Others"],
"Mair Rajput Swarnkar": ["Others"],
"Majabi": ["Others"],
"Mala": ["Others"],
"Mali": ["Others"],
"Mallah": ["Others"],
"Malwani": ["Others"],
"Mangalorean": ["Others"],
"Manipuri": ["Others"],
"Mannan ": ["Others"],
"Mapila": ["Others"],
"Maratha": ["Others"],
"Maratha Kshatriya": ["Others"],
"Maruthuvar": ["Others"],	
"Matang": ["Others"],	
"Mathur": ["Others"],
"Mathur Vaishya": ["Others"],	
"Maurya / Shakya": ["Others"],	
"Meena": ["Others"],	
"Meenavar": ["Others"],	
"Meghwal": ["Others"],	
"Mehra": ["Others"],	
"Meru Darji": ["Others"],	
"Mogaveera": ["Others"],	
"Mudaliyar": ["Others"],	
"Mudiraj": ["Others"],	
"Munnuru Kapu": ["Others"],	
"Muthuraja": ["Others"],	
"Naagavamsam": ["Others"],
"Nabit": ["Others"],
"Nadar": ["Others"],
"Nagaralu": ["Others"],
"Nai": ["Others"],
"Naicker": ["Vanniya Kula Kshatriyar", "Naicker - Others"],
"Naidu": ["Others"],
"Naik": ["Others"],	
"Nair": ["Veluthedathu Nair", "Vilakithala Nair",""],
"Namasudra / Namassej": ["Others"],
"Nambiar": ["Others"],
"Namdarlu": ["Others"],
"Nanjil": ["Others"],
"Nayakar": ["Others"],
"Neeli": ["Neeli", "Neeli Saali","Others"],
"Nema": ["Others"],
"Nepali": ["Others"],
"Nessi": ["Others"],
"Ontari": ["Others"],
"Oswal": ["Others"],
"Otari": ["Others"],
"Othuvaar": ["Others"],
"Padmasali": ["Others"],
"Padmavati Porwal": ["Others"],
"Pagadala": ["Others"],
"Pallan / Devandra Kula Vellalan": ["Others"],
"Panchal": ["Others"],
"Pandaram": ["Others"],
"Parkava Kulam": ["Others"],
"Partraj": ["Others"],
"Parsi": ["Others"],
"Paswan ": ["Others"],
"Pattusali": ["Others"],
"Patwa": ["Others"],
"Perika": ["Others"],
"Pillai": ["Others"],
"Porwal": ["Others"],
"Poundra": ["Others"],
"Prajapati": ["Others"],
"Pulaya": ["Others"],
"Raigar": ["Others"],
"Rajaka": ["Others"],
"Rajastani": ["Others"],
"Rajbhar": ["Others"],
"Rajbonshi": ["Others"],
"Rajpurohit": ["Others"],
"Rajput": ["Others"],
"Ramanandi": ["Others"],
"Ramdasia": ["Others"],
"Ramgariah": ["Others"],
"Ramoshi": ["Others"],
"Rastogi": ["Others"],
"Rathi": ["Others"],
"Rauniar": ["Others"],
"Ravidasia": ["Others"],
"Rawat": ["Others"],
"Reddy": ["Others"],

"Relli": ["Others"],
"Rohit / Chamar": ["Others"],
"SC": ["Others"],
"SKP": ["Others"],
"ST": ["Others"],
"Sadgope": ["Others"],
"Sagara": ["Others"],
"Saha": ["Others"],
"Saini": ["Others"],
"Saiva Pillai": ["Others"],
"Saliya": ["Others"],
"Samagar": ["Others"],
"Sambava": ["Others"],
"Sathwara": ["Others"],
"Satnami": ["Others"],
"Savji": ["Others"],
"Senai Thalaivar": ["Others"],
"Senguntha Mudaliyar": ["Others"],
"Sengunthar/Kaikolar": ["Others"],
"Settibalija": ["Others"],
"Shettigar": ["Others"],
"Shilpkar": ["Others"],
"Shimpi/Namdev": ["Others"],
"Sindhi": ["Others"],
"Sonar": ["Others"],
"Sonkar": ["Others"],
"Sourashtra": ["Others"],
"Thakore": ["Others"],
"Thakkar": ["Others"],
"Telugupatti": ["Others"],
"Teli": ["Others"],
"Telaga": ["Others"],
"Tantubai": ["Others"],
"Tanti": ["Others"],
"Tamboli": ["Others"],
"Swakula Sali": ["Others"],
"Suthar": ["Others"],
"Surya Balija": ["Others"],
"Sunari": ["Others"],
"Sugali ": ["Others"],
"Srisayana": ["Others"],
"Parit": ["Others"],
"Paravan / Bharatar": ["Others"],
"Thakur": ["Others"],
"Thandan": ["Others"],
"Thigala": ["Others"],
"Thiyya": ["Others"],
"Thiyya Thandan": ["Others"],
"Thogata Veera Kshatriya": ["Others"],
"Thota": ["Others"],
"Togata": ["Others"],
"Turupu Kapu": ["Others"],
"Tili": ["Others"],
"Tonk Kshatriya": ["Others"],
"Ummar": ["Others"],
"Vada Balija": ["Others"],
"Vadambar": ["Others"],
"Vaddera": ["Others"],
"Vadugan": ["Others"],
"Vaish": ["Others"],
"Vaishnav": ["Others"],
"Valluvan": ["Others"],
"Vaishya Vani": ["Others"],
"Valmiki": ["Others"],
"Vani": ["Others"],
"Vaniyar": ["Others"],
"Vanjara": ["Others"],
"Vanjari": ["Others"],
"Vannia Kula Kshatriyar": ["Others"],
"Varshney<": ["Others"],
"Veera Saivam": ["Others"],
"Velaan": ["Others"],
"Velama": ["Others"],
"Vettuvan": ["Others"],
"Vijayvargia": ["Others"],
"Vellalar": ["Others"],
"Vishwakarma": ["Others"],
"Viswabrahmin": ["Others"],
"Vokkaliga": ["Others"],
"Vysya": ["Others"],
"Yadav": ["Others"],
"Yadava Naidu": ["Others"],
"Yellapu": ["Others"],
"Other Caste": ["Others"],
"Don't wish to specify": ["Others"],

    }
}
window.onload = function () {
    var countySel = document.getElementById("countySel"),
        stateSel = document.getElementById("stateSel"),
        districtSel = document.getElementById("districtSel");
    for (var country in stateObject) {
        countySel.options[countySel.options.length] = new Option(country, country);
    }
    countySel.onchange = function () {
        stateSel.length = 1; // remove all options bar first
        districtSel.length = 1; // remove all options bar first
        if (this.selectedIndex < 1) return; // done   
        for (var state in stateObject[this.value]) {
            stateSel.options[stateSel.options.length] = new Option(state, state);
        }
    }
    countySel.onchange(); // reset in case page is reloaded
    stateSel.onchange = function () {
        districtSel.length = 1; // remove all options bar first
        if (this.selectedIndex < 1) return; // done   
        var district = stateObject[countySel.value][this.value];
        for (var i = 0; i < district.length; i++) {
            districtSel.options[districtSel.options.length] = new Option(district[i], district[i]);
        }
    }
}
</script>